result_map = {
    'home_win' : 1,
    'draw'     : 0,
    'away_win' : 2
}



K_map = {
    # Major tournaments — K = 60
    'FIFA World Cup'                            : 60,
    'UEFA Euro'                                 : 60,
    'Copa América'                              : 60,
    'African Cup of Nations'                    : 60,
    'AFC Asian Cup'                             : 60,
    'Gold Cup'                                  : 60,
    'CONCACAF Championship'                     : 60,
    'Confederations Cup'                        : 60,
    'Oceania Nations Cup'                       : 60,
    'Olympic Games'                             : 60,
    'Asian Games'                               : 60,
    'CONMEBOL–UEFA Cup of Champions'            : 60,

    # World Cup & Major Qualification — K = 50
    'FIFA World Cup qualification'              : 50,
    'UEFA Euro qualification'                   : 50,
    'African Cup of Nations qualification'      : 50,
    'AFC Asian Cup qualification'               : 50,
    'Gold Cup qualification'                    : 50,
    'CONCACAF Championship qualification'       : 50,
    'Copa América qualification'                : 50,
    'Oceania Nations Cup qualification'         : 50,
    'CONCACAF Nations League qualification'     : 50,
    'AFF Championship qualification'            : 50,
    'AFC Challenge Cup qualification'           : 50,
    'Arab Cup qualification'                    : 50,
    'COSAFA Cup qualification'                  : 50,
    'EAFF Championship qualification'           : 50,
    'CONIFA World Football Cup qualification'   : 50,
    'ASEAN Championship qualification'          : 50,

    # Regional tournaments — K = 40
    'UEFA Nations League'                       : 40,
    'CONCACAF Nations League'                   : 40,
    'AFF Championship'                          : 40,
    'ASEAN Championship'                        : 40,
    'AFC Challenge Cup'                         : 40,
    'EAFF Championship'                         : 40,
    'WAFF Championship'                         : 40,
    'SAFF Cup'                                  : 40,
    'Gulf Cup'                                  : 40,
    'Arab Cup'                                  : 40,
    'COSAFA Cup'                                : 40,
    'CECAFA Cup'                                : 40,
    'CFU Caribbean Cup'                         : 40,
    'CFU Caribbean Cup qualification'           : 40,
    'UNCAF Cup'                                 : 40,
    'CCCF Championship'                         : 40,
    'Pan American Championship'                 : 40,
    'Southeast Asian Games'                     : 40,
    'South Asian Games'                         : 40,
    'South Pacific Games'                       : 40,
    'Pacific Games'                             : 40,
    'All-African Games'                         : 40,
    'African Friendship Games'                  : 40,
    'Central American and Caribbean Games'      : 40,
    'Bolivarian Games'                          : 40,
    'East Asian Games'                          : 40,
    'Far Eastern Championship Games'            : 40,
    'GaNEFo'                                    : 40,
    'Inter-Allied Games'                        : 40,
    'Inter Games'                               : 40,
    'Indian Ocean Island Games'                 : 40,
    'Island Games'                              : 40,
    'Pacific Mini Games'                        : 40,
    'South Pacific Mini Games'                  : 40,
    'Melanesia Cup'                             : 40,

    # Invitational & regional cups — K = 30
    'British Home Championship'                 : 30,
    'Nordic Championship'                       : 30,
    'Baltic Cup'                                : 30,
    'Balkan Cup'                                : 30,
    'Central European International Cup'        : 30,
    'Merdeka Tournament'                        : 30,
    'King\'s Cup'                               : 30,
    'Amílcar Cabral Cup'                        : 30,
    'Muratti Vase'                              : 30,
    'Korea Cup'                                 : 30,
    'Kirin Cup'                                 : 30,
    'Kirin Challenge Cup'                       : 30,
    'Nehru Cup'                                 : 30,
    'Cyprus International Tournament'           : 30,
    'Malta International Tournament'            : 30,
    'West African Cup'                          : 30,
    'UDEAC Cup'                                 : 30,
    'UNIFFAC Cup'                               : 30,
    'CAFA Nations Cup'                          : 30,
    'Nile Basin Tournament'                     : 30,
    'Windward Islands Tournament'               : 30,
    'Dynasty Cup'                               : 30,
    'Lunar New Year Cup'                        : 30,
    'Merlion Cup'                               : 30,
    'Superclásico de las Américas'              : 30,
    'Intercontinental Cup'                      : 30,
    'Tournoi de France'                         : 30,
    'Brazil Independence Cup'                   : 30,
    'USA Cup'                                   : 30,
    'Vietnam Independence Cup'                  : 30,
    'Indonesia Tournament'                      : 30,
    'Mundialito'                                : 30,
    'Trans-Tasman Cup'                          : 30,
    'Rous Cup'                                  : 30,
    'Peace Cup'                                 : 30,
    'King Hassan II Tournament'                 : 30,
    'Hassan II Trophy'                          : 30,
    'Four Nations Tournament'                   : 30,
    'Tri Nation Tournament'                     : 30,
    'Tri-Nations Series'                        : 30,
    'Nations Cup'                               : 30,
    'Atlantic Cup'                              : 30,
    'MSG Prime Minister\'s Cup'                 : 30,
    'Prime Minister\'s Cup'                     : 30,
    'Southeast Asian Peninsular Games'          : 30,
    'Simba Tournament'                          : 30,
    'Dakar Tournament'                          : 30,
    'Tournament Burkina Faso'                   : 30,
    'Jordan International Tournament'           : 30,
    'Beijing International Friendship Tournament': 30,
    'Guangzhou International Friendship Tournament': 30,
    'United Arab Emirates Friendship Tournament': 30,
    'FIFA Series'                               : 30,

    # South American historic cups — K = 25
    'Copa Lipton'                               : 25,
    'Copa Newton'                               : 25,
    'Copa Roca'                                 : 25,
    'Copa Rio Branco'                           : 25,
    'Copa Oswaldo Cruz'                         : 25,
    'Copa Carlos Dittborn'                      : 25,
    'Copa Bernardo O\'Higgins'                  : 25,
    'Copa Artigas'                              : 25,
    'Copa Félix Bogado'                         : 25,
    'Copa Ramón Castilla'                       : 25,
    'Copa Paz del Chaco'                        : 25,
    'Copa Premio Honor Uruguayo'                : 25,
    'Copa Premio Honor Argentino'               : 25,
    'Copa Chevallier Boutell'                   : 25,
    'Copa del Pacífico'                         : 25,
    'Copa Juan Pinto Durán'                     : 25,
    'Copa Confraternidad'                       : 25,

    # CONIFA & non-FIFA — K = 20
    'CONIFA World Football Cup'                 : 20,
    'CONIFA European Football Cup'              : 20,
    'CONIFA South America Football Cup'         : 20,
    'CONIFA Africa Football Cup'                : 20,
    'CONIFA Asia Cup'                           : 20,
    'Viva World Cup'                            : 20,
    'FIFI Wild Cup'                             : 20,
    'ELF Cup'                                   : 20,
    'NF-Board World Cup'                        : 20,

    # Friendlies and everything else — K = 20
    'Friendly'                                  : 20,
    'Soccer Ashes'                              : 20,
    'SKN Football Festival'                     : 20,
    'Palestine Cup'                             : 20,
    'Miami Cup'                                 : 20,
    'Marlboro Cup'                              : 20,
    'Dunhill Cup'                               : 20,
    'Millennium Cup'                            : 20,
    'Kuneitra Cup'                              : 20,
    'Scania 100 Tournament'                     : 20,
    'Navruz Cup'                                : 20,
    'Afro-Asian Games'                          : 20,
    'Great Wall Cup'                            : 20,
    'Matthews Cup'                              : 20,
    'Dragon Cup'                                : 20,
    'OSN Cup'                                   : 20,
    'Unity Cup'                                 : 20,
    'Corsica Cup'                               : 20,
    'VFF Cup'                                   : 20,
    'ABCS Tournament'                           : 20,
    'NAFC Championship'                         : 20,
    'NAFU Championship'                         : 20,
    'Joe Robbie Cup'                            : 20,
    'Tynwald Hill Tournament'                   : 20,
    'Three Nations Cup'                         : 20,
    'Hungary Heritage Cup'                      : 20,
    'Atlantic Heritage Cup'                     : 20,
    'World Unity Cup'                           : 20,
    'Marianas Cup'                              : 20,
    'Four Nations\' Cup'                        : 20,
    'Cup of Ancient Civilizations'              : 20,
    'Niamh Challenge Cup'                       : 20,
    'Phillip Seaga Cup'                         : 20,
    'Zambian Independence Tournament'           : 20,
    'ConIFA Challenger Cup'                     : 20,
    'Real Madrid 75th Anniversary Cup'          : 20,
    'TIFOCO Tournament'                         : 20,
    'Évence Coppée Trophy'                      : 20,
    'Open International Championship'           : 20,
    'FIFA 75th Anniversary Cup'                 : 20,
    'The Other Final'                           : 20,
    'Benedikt Fontana Cup'                      : 20,
    'Mahinda Rajapaksa Cup'                     : 20,
    'Mauritius Four Nations Cup'                : 20,
    'CONIFA World Football Cup qualification'   : 20,
    'Copa América qualification'                : 20,
    'Default'                                   : 20,
}